server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mcs?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: mcsadmin
    password: mcs1234
    driver-class-name: org.mariadb.jdbc.Driver