server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mcs?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: mcsadmin
    password: mcs1234
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30